// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TripsApp.Data;

#nullable disable

namespace EFCoreMvcApp.Migrations
{
    [DbContext(typeof(TripContext))]
    [Migration("20250321020038_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("TripsApp.Models.Trip", b =>
                {
                    b.Property<int>("TripId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Accommodation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccommodationEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccommodationPhone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Activity1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Activity2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Activity3")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("TripId");

                    b.ToTable("Trips");
                });
#pragma warning restore 612, 618
        }
    }
}
